spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      x-forwarded:
        enabled: false
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: rabbit-server
          uri:  lb://rabbit-server
          predicates:
            - Path=/rabbit/**
        - id: product-server
          uri:  lb://product-server
          predicates:
            - Path=/product/**
        - id: wechat-server
          uri: http://192.168.174.131:7005
#          uri:  lb://wechat-server
          predicates:
            - Path=/wechat/**
#        后台管理服务接口
        - id: manager-server
          uri: http://192.168.174.1:7016
#          uri:  lb://wechat-server
          predicates:
            - Path=/manager/**
        - id: sysadmin-server
          uri:  lb://sysadmin-server
          predicates:
            - Path=/sysadmin/**
        - id: swaggerui-server
          uri:  lb://swaggerui-server
          predicates:
            - Path=/swaggerui/**
        - id: logutil-server
          uri:  lb://logutil-server
          predicates:
            - Path=/logutil/**
        - id: author-server
          uri:  lb://author-server
          predicates:
            - Path=/author/**
        - id: common-server
          uri:  lb://common-server
          predicates:
            - Path=/common/**
        - id: config-server
          uri:  lb://config-server
          predicates:
            - Path=/config/**
        - id: sidecar-python
          uri:  lb://sidecar-python
          predicates:
            - Path=/python/**
        - id: qaserver-server
          uri:  lb://qaserver-server
          predicates:
            - Path=/qaserver/**
        - id: hadoop-common-server
          uri:  lb://hadoop-common-server
          predicates:
            - Path=/hadoop-common/**
server:
  port: 5070
  servlet:
    context-path: /gateway
  address: 0.0.0.0
eureka:
  client:
    service-url:
      defaultZone: http://192.168.174.131:5060/eureka/eureka
