
spring:
  application:
    name: swaggerui-server
server:
  port: 7003
  servlet:
    context-path: /swaggerui
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5060/eureka/eureka
